// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return homolog;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions prod = FirebaseOptions(
    apiKey: 'AIzaSyD0SSxQp4b2lns1q8pTQOC3V9nPEf6kG9E',
    appId: '1:466406072369:web:dab02862b93906d023f510',
    messagingSenderId: '466406072369',
    projectId: 'intranet-maispet',
    authDomain: 'intranet-maispet.firebaseapp.com',
    databaseURL: 'https://intranet-maispet-default-rtdb.firebaseio.com',
    storageBucket: 'intranet-maispet.appspot.com',
    measurementId: 'G-X02QM1FRJR',
  );

  static const FirebaseOptions homolog = FirebaseOptions(
    apiKey: 'AIzaSyDnJtwGJM81DFVjZTix_ehDiPhKziNgfms',
    appId: '1:79806760493:web:e681a2955bb8a1e1e2daa4',
    messagingSenderId: '79806760493',
    projectId: 'maispet-testes',
    authDomain: 'maispet-testes.firebaseapp.com',
    databaseURL: 'https://maispet-testes-default-rtdb.firebaseio.com',
    storageBucket: 'maispet-testes.appspot.com',
    measurementId: 'G-369NR4H85B',
  );

}
